# -*- coding: utf-8 -*-
"""PyTorch Model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mJJlarW-cFTKkuIBwZKOvi2XEeVfKEtY

Using pip to install TorchVision so we can download our resnet18 model
"""

pip install torchvision

"""Downloading a pretrained model of resnet18 into an empty folder named 'resnet18" as a file namde "resnet18". Before that we are optimizing it for a mobile device"""

import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torchvision.models.resnet18(pretrained=True)
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
traced_script_module_optimized = optimize_for_mobile(traced_script_module)
traced_script_module_optimized._save_for_lite_interpreter("/content/resnet18/resnet18.pt")